//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azul.PontualidadeANAC
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHistoricoAnac", Namespace="http://schemas.datacontract.org/2004/07/ITGlobalServices.Pontualidade.Anac.Entiti" +
        "es")]
    public partial class RequestHistoricoAnac : object
    {
        
        private string destinoField;
        
        private string empresaField;
        
        private string equipmentTypeField;
        
        private int num_vooField;
        
        private string origemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destino
        {
            get
            {
                return this.destinoField;
            }
            set
            {
                this.destinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empresa
        {
            get
            {
                return this.empresaField;
            }
            set
            {
                this.empresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string equipmentType
        {
            get
            {
                return this.equipmentTypeField;
            }
            set
            {
                this.equipmentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_voo
        {
            get
            {
                return this.num_vooField;
            }
            set
            {
                this.num_vooField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string origem
        {
            get
            {
                return this.origemField;
            }
            set
            {
                this.origemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnacWS", Namespace="http://schemas.datacontract.org/2004/07/ITGlobalServices.Pontualidade.Anac.Entiti" +
        "es")]
    public partial class AnacWS : object
    {
        
        private string cod_iata_destinoField;
        
        private string cod_iata_origemField;
        
        private bool historico_validoField;
        
        private string mensagemField;
        
        private string nom_empresa_aereaField;
        
        private System.Nullable<int> num_vooField;
        
        private System.Nullable<int> prc_atraso_sup_30_minField;
        
        private System.Nullable<int> prc_atraso_sup_60_minField;
        
        private System.Nullable<int> prc_cancelamentoField;
        
        private string tag_textField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_iata_destino
        {
            get
            {
                return this.cod_iata_destinoField;
            }
            set
            {
                this.cod_iata_destinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_iata_origem
        {
            get
            {
                return this.cod_iata_origemField;
            }
            set
            {
                this.cod_iata_origemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool historico_valido
        {
            get
            {
                return this.historico_validoField;
            }
            set
            {
                this.historico_validoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_empresa_aerea
        {
            get
            {
                return this.nom_empresa_aereaField;
            }
            set
            {
                this.nom_empresa_aereaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> num_voo
        {
            get
            {
                return this.num_vooField;
            }
            set
            {
                this.num_vooField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> prc_atraso_sup_30_min
        {
            get
            {
                return this.prc_atraso_sup_30_minField;
            }
            set
            {
                this.prc_atraso_sup_30_minField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> prc_atraso_sup_60_min
        {
            get
            {
                return this.prc_atraso_sup_60_minField;
            }
            set
            {
                this.prc_atraso_sup_60_minField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> prc_cancelamento
        {
            get
            {
                return this.prc_cancelamentoField;
            }
            set
            {
                this.prc_cancelamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag_text
        {
            get
            {
                return this.tag_textField;
            }
            set
            {
                this.tag_textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Azul.PontualidadeANAC.IServiceListarHistoricoAnac")]
    public interface IServiceListarHistoricoAnac
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceListarHistoricoAnac/ListarHistoricoAnacSOAP", ReplyAction="http://tempuri.org/IServiceListarHistoricoAnac/ListarHistoricoAnacSOAPResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Azul.PontualidadeANAC.AnacWS>> ListarHistoricoAnacSOAPAsync(System.Collections.Generic.List<Azul.PontualidadeANAC.RequestHistoricoAnac> listaRequestHistoricoAnac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceListarHistoricoAnac/ListarHistoricoAnacJSON", ReplyAction="http://tempuri.org/IServiceListarHistoricoAnac/ListarHistoricoAnacJSONResponse")]
        System.Threading.Tasks.Task<string> ListarHistoricoAnacJSONAsync(System.Collections.Generic.List<Azul.PontualidadeANAC.RequestHistoricoAnac> listaRequestHistoricoAnac, System.Nullable<System.DateTime> flightDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceListarHistoricoAnac/GetFlightTag", ReplyAction="http://tempuri.org/IServiceListarHistoricoAnac/GetFlightTagResponse")]
        System.Threading.Tasks.Task<string> GetFlightTagAsync(Azul.PontualidadeANAC.RequestHistoricoAnac reqHistAnac, System.DateTime flightDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface IServiceListarHistoricoAnacChannel : Azul.PontualidadeANAC.IServiceListarHistoricoAnac, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class ServiceListarHistoricoAnacClient : System.ServiceModel.ClientBase<Azul.PontualidadeANAC.IServiceListarHistoricoAnac>, Azul.PontualidadeANAC.IServiceListarHistoricoAnac
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceListarHistoricoAnacClient() : 
                base(ServiceListarHistoricoAnacClient.GetDefaultBinding(), ServiceListarHistoricoAnacClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceListarHistoricoAnac.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceListarHistoricoAnacClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceListarHistoricoAnacClient.GetBindingForEndpoint(endpointConfiguration), ServiceListarHistoricoAnacClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceListarHistoricoAnacClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceListarHistoricoAnacClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceListarHistoricoAnacClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceListarHistoricoAnacClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceListarHistoricoAnacClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Azul.PontualidadeANAC.AnacWS>> ListarHistoricoAnacSOAPAsync(System.Collections.Generic.List<Azul.PontualidadeANAC.RequestHistoricoAnac> listaRequestHistoricoAnac)
        {
            return base.Channel.ListarHistoricoAnacSOAPAsync(listaRequestHistoricoAnac);
        }
        
        public System.Threading.Tasks.Task<string> ListarHistoricoAnacJSONAsync(System.Collections.Generic.List<Azul.PontualidadeANAC.RequestHistoricoAnac> listaRequestHistoricoAnac, System.Nullable<System.DateTime> flightDate)
        {
            return base.Channel.ListarHistoricoAnacJSONAsync(listaRequestHistoricoAnac, flightDate);
        }
        
        public System.Threading.Tasks.Task<string> GetFlightTagAsync(Azul.PontualidadeANAC.RequestHistoricoAnac reqHistAnac, System.DateTime flightDate)
        {
            return base.Channel.GetFlightTagAsync(reqHistAnac, flightDate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceListarHistoricoAnac))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceListarHistoricoAnac))
            {
                return new System.ServiceModel.EndpointAddress("http://teste-webservices.azul.corp/WSPontualidadeANAC/ServiceListarHistorico.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceListarHistoricoAnacClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceListarHistoricoAnac);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceListarHistoricoAnacClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceListarHistoricoAnac);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceListarHistoricoAnac,
        }
    }
}
